"""
Django settings for auth_service project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'msbc_rbac.accounts',
    'msbc_rbac.core',
    'auth_app',
    'rest_framework',
    'drf_yasg',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'auth_service.middleware.cache_control.NoCacheMiddleware',  # Cache control for sensitive data - EARLY
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For production static files
    'corsheaders.middleware.CorsMiddleware',
    'auth_service.middleware.rate_limiting.RateLimitMiddleware',  # Rate limiting
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'auth_service.middleware.jwt_auth.JWTAuthenticationMiddleware',  # JWT authentication - AFTER Django auth so it overwrites AnonymousUser
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auth_service.middleware.tenant_context.TenantContextMiddleware',  # Multi-tenant RLS
    'msbc_rbac.core.middleware.CurrentTenantMiddleware',  # RBAC Tenant resolution
    'msbc_rbac.core.services.RBACMiddleware.RBACMiddleware',  # RBAC Module/SubModule interceptor
    'msbc_rbac.core.exception_middleware.JSONExceptionMiddleware',  # MUST BE LAST
]

# CSRF and Security Settings
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://127.0.0.1:8000,http://localhost:8000,http://192.168.71.244').split(',')
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
# print(SECURE_SSL_REDIRECT)
ROOT_URLCONF = 'auth_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auth_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    },
    # -----------------------------------------------------------------------
    # rbac_project — owns all msbc_rbac tables (accounts.*, core.*, tenant)
    # The RBACDatabaseRouter routes all msbc_rbac models here.
    # The journies (default) DB must NEVER contain RBAC tables.
    # -----------------------------------------------------------------------
    'rbac': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('RBAC_DB_NAME', default='rbac_project'),
        'USER': config('RBAC_DB_USER', default=config('DB_USER')),
        'PASSWORD': config('RBAC_DB_PASSWORD', default=config('DB_PASSWORD')),
        'HOST': config('RBAC_DB_HOST', default=config('DB_HOST')),
        'PORT': config('RBAC_DB_PORT', default=config('DB_PORT')),
    },
}

# -----------------------------------------------------------------------
# Database Router — enforces DB separation.
# msbc_rbac.core + msbc_rbac.accounts  →  'rbac'  database
# auth_app and all Django built-ins     →  'default' (auth_service) DB
# -----------------------------------------------------------------------
DATABASE_ROUTERS = ['auth_service.db_router.RBACDatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (minimal for API service)
BASE_ROUTE = config('BASE_ROUTE', default='')
STATIC_URL = f'{BASE_ROUTE}/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Only for admin/swagger UI static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DYNAMIC_LOG_PATH = os.path.join(BASE_DIR, "Logs")

# Create email files directory if it doesn't exist
EMAIL_FILES_DIR = os.path.join(BASE_DIR, 'email_files')
if not os.path.exists(EMAIL_FILES_DIR):
    os.makedirs(EMAIL_FILES_DIR)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if config('DEBUG', default=False, cast=bool) else 'WARNING',
    },
}

FORCE_SCRIPT_NAME = BASE_ROUTE

# Frontend URL for invitation links
FRONTEND_URL = config('FRONTEND_URL', default='http://192.168.71.244/login')

# JWT Configuration
JWT_PRIVATE_KEY_PATH = config('JWT_PRIVATE_KEY_PATH')
JWT_PUBLIC_KEY_PATH = config('JWT_PUBLIC_KEY_PATH')
JWT_ISSUER = config('JWT_ISSUER')
JWT_ALGORITHM = config('JWT_ALGORITHM')
JWT_KID = config('JWT_KID')
JWT_AUDIENCE = config('JWT_AUDIENCE')
AUTH_SERVICE_URL = config('AUTH_SERVICE_URL')

# Password Encryption Key (same as frontend)
PASSWORD_CRYPT_KEY = config('PASSWORD_CRYPT_KEY')

# USE_X_FORWARDED_HOST = True  # Disabled for static files
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Disabled for static files

# Custom User Model
AUTH_USER_MODEL = 'auth_app.UserModel'

# Cache Configuration for Rate Limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'rate-limit-cache',
    }
}

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'EXCEPTION_HANDLER': 'msbc_rbac.core.drf_exception_handler.custom_exception_handler',
}

# Swagger JWT Authentication
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'none',
    'DEEP_LINKING': True,
    'SHOW_EXTENSIONS': True,
    'SHOW_COMMON_EXTENSIONS': True,
}

# Redis Configuration for Streams
REDIS_HOST = config('REDIS_HOST', default='localhost')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
REDIS_DB = config('REDIS_DB', default=0, cast=int)
REDIS_STREAM_USERS = config('REDIS_STREAM_USERS', default='journies:stream:users')

# JWT Public Paths (configurable for microservices)
JWT_PUBLIC_PATHS = [
    '/api/v1/users/login/',
    '/api/v1/users/signup/',
    '/api/v1/users/verify_token/',
    '/api/v1/users/refresh_token/',
    '/api/email-files/',
    '/.well-known/jwks.json',
    '/health/',
    '/swagger/',
    '/redoc/',
    '/static/',
    '/admin/'
]

# Bypass RBAC logic for these pre-auth endpoints
BYPASS_PATH_PREFIXES = JWT_PUBLIC_PATHS


# Email Configuration - SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default='True', cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='compass@journies.ai')
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')
COMPASS_SERVICE_URL = config('COMPASS_SERVICE_URL', default='http://localhost:3001')

# Password Encryption Configuration
PASSWORD_CRYPT_KEY = config('PASSWORD_CRYPT_KEY')
SALT = config('SALT')

# Logo URL for email templates
LOGO_URL = config('LOGO_URL', default='http://localhost:8001/static/images/Journies_logo.png')
