# Generated by Django 4.2.25 on 2025-11-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_add_unique_phone_number'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tokenblacklist',
            new_name='journies_to_user_id_6659f7_idx',
            old_name='journies_to_user_id_b8e5a5_idx',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
