# Generated by Django 4.2.25 on 2025-11-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_nullable_tenant_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
