# Generated by Django 4.2.25 on 2025-11-20 05:57

from django.db import migrations, models


def set_default_names(apps, schema_editor):
    """Set default name for null/empty first_name and last_name"""
    UserModel = apps.get_model('auth_app', 'UserModel')
    UserModel.objects.filter(first_name__isnull=True).update(first_name='User')
    UserModel.objects.filter(first_name='').update(first_name='User')
    UserModel.objects.filter(last_name__isnull=True).update(last_name='Account')
    UserModel.objects.filter(last_name='').update(last_name='Account')


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_usermodel_terms_accepted'),
    ]

    operations = [
        migrations.RunPython(set_default_names),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(blank=False, max_length=100, null=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(blank=False, max_length=100, null=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
