# Generated by Django 4.2.25 on 2025-11-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_usermodel_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='plan',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_onboarding_complete',
            field=models.BooleanField(default=False, help_text='All onboarding steps completed'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_plan_purchased',
            field=models.BooleanField(default=False, help_text='User has active subscription plan'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Account active/suspended status'),
        ),
    ]
