# Generated by Django 4.2.25 on 2025-11-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_remove_tenant_plan_usermodel_is_onboarding_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role_id',
            field=models.UUIDField(blank=True, help_text='Role ID from Compass service', null=True),
        ),
    ]
