# Generated by Django 4.2.25 on 2026-01-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_usermodel_email_alter_usermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='department_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
