# Generated by Django 4.2.25 on 2026-02-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_usermodel_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
