# Generated by Django 4.2.25 on 2026-02-19 13:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_usermodel_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='tenant',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Name (2-50 characters)', max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters long')]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Staff access flag'),
        ),
    ]
